<?php /** @var \ParadoxLabs\PageBuilderWidgets\Block\Category\CategoriesList $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->getCategoryCollection() && $block->getCategoryCollection()->getSize()): ?>
    <?php $categories = $block->getCategoryCollection()->getItems() ?>
    <div class="block widget block-products-list block-categories-list grid">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-items widget-product-grid">
                    <?php foreach ($categories as $category): ?>
                        <li class="product-item">
                            <?php $image = $block->getImage($category); ?>
                            <div class="product-item-info">
                                <a href="<?= $escaper->escapeHtmlAttr($category->getUrl()) ?>"
                                   class="product-item-photo"
                                   title="<?= $escaper->escapeHtmlAttr($category->getName()) ?>">
                                    <img
                                        src="<?= $escaper->escapeHtmlAttr($image->getUrl()) ?>"
                                        alt="<?= $escaper->escapeHtmlAttr($category->getName()) ?>"
                                        loading="lazy"
                                        width="<?= $escaper->escapeHtmlAttr($image->getWidth()) ?>"
                                        style="aspect-ratio: <?= $escaper->escapeHtmlAttr(
                                            $image->getWidth() . ' / ' . $image->getHeight()
                                        ) ?>;"
                                    />
                                </a>
                                <?php if ($block->getData('show_name') === 'true'): ?>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $escaper->escapeHtml($category->getName()) ?>"
                                               href="<?= $escaper->escapeHtmlAttr($category->getUrl()) ?>"
                                               class="product-item-link">
                                                <?= $escaper->escapeHtml($category->getName()) ?>
                                            </a>
                                        </strong>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
