<?php /** @var \ParadoxLabs\PageBuilderWidgets\Block\Category\CategoriesList $block */ ?>
<?php if ($block->getCategoryCollection() && $block->getCategoryCollection()->getSize()) : ?>
    <?php $categories = $block->getCategoryCollection()->getItems() ?>
    <div class="block widget block-products-list block-categories-list grid">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-items widget-product-grid">
                    <?php foreach ($categories as $category) : ?>
                        <li class="product-item">
                            <?php $image = $block->getImage($category); ?>
                            <div class="product-item-info">
                                <a href="<?= $block->escapeUrl($category->getUrl()) ?>"
                                   class="product-item-photo"
                                   title="<?= $block->escapeHtmlAttr($category->getName()) ?>">
                                    <img
                                        src="<?= $image->getUrl() ?>"
                                        alt="<?= $block->escapeHtmlAttr($category->getName()) ?>"
                                        loading="lazy"
                                        width="<?= $image->getWidth() ?>"
                                        style="aspect-ratio: <?= $image->getWidth() . ' / ' . $image->getHeight() ?>;"
                                    />
                                </a>
                                <?php if ($block->getData('show_name') === 'true'): ?>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtml($category->getName()) ?>"
                                               href="<?= $block->escapeUrl($category->getUrl()) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($category->getName()) ?>
                                            </a>
                                        </strong>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
