<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use ParadoxLabs\PageBuilderWidgets\Block\Category\CategoriesList;

/** @var CategoriesList $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

?>
<?php if ($block->getCategoryCollection() && $block->getCategoryCollection()->getSize()): ?>
    <?php
    $categories = $block->getCategoryCollection()->getItems();
    $title = $block->getTitle() ?: __('Categories');
    if (!$itemCount = count($categories)) {
        return '';
    }
    ?>
    <script>
        'use strict';

        function initSliderComponent() {
            return {
                active: 0,
                itemCount: 0,
                getSlider() {
                    return this.$root.querySelector('.js_slides');
                },
                pageSize: 6,
                pageFillers: 0,
                calcPageSize() {
                    const slider = this.getSlider();
                    if (slider) {
                        this.itemCount = slider.querySelectorAll('.js_slide').length;
                        this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                        this.pageFillers = (
                                               this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                                           ) - this.itemCount;
                    }
                },
                calcActive() {
                    const slider = this.getSlider();
                    if (slider) {
                        const sliderItems = this.itemCount + this.pageFillers;
                        const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                        this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                    }
                },
                scrollPrevious() {
                    this.scrollTo(this.active - this.pageSize);
                },
                scrollNext() {
                    this.scrollTo(this.active + this.pageSize);
                },
                scrollTo(idx) {
                    const slider = this.getSlider();
                    if (slider) {
                        const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                        slider.scrollLeft = Math.floor(slideWidth) * idx;
                        this.active = idx;
                    }
                },
                skipCarouselToNavigation(navSelector) {
                    const element = document.getElementById(navSelector)
                    if (element) {
                        element.scrollIntoView({behavior: 'smooth', block: 'end'});
                        const button = element.querySelector('button:not([disabled])');
                        this.$nextTick(() => button && button.focus({preventScroll: true}))
                    }
                }
            }
        }
    </script>
    <section
        class="text-gray-700 body-font"
        x-data="initSliderComponent()"
        x-init="calcPageSize();"
        x-id="['slider-nav', 'slider-desc', 'slider-id']"
        @resize.window.debounce="calcPageSize(); $nextTick(() => { calcActive() })"
        role="group"
        aria-roledescription="<?= $escaper->escapeHtmlAttr(__('Carousel')) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Carousel: %1', $title)) ?>"
        :aria-describedby="$id('slider-desc')"
    >
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <h3 class="text-xl"><?= $block->escapeHtml(__($block->getTitle())) ?></h3>
            </div>
        <?php endif ?>

        <div class="relative">
            <span class="sr-only" :id="$id('slider-desc')" tabindex="-1">
                <?= $escaper->escapeHtml(__('Use the navigation buttons to browse categories in the carousel.')) ?>
            </span>

            <div class="flex-none relative w-full overflow-x-hidden">
                <div
                    class="relative flex flex-nowrap w-full overflow-auto js_slides snap md:px-1 xl:px-2 leading-none"
                    @scroll.debounce="calcActive"
                >
                    <?php foreach ($categories as $category): ?>
                        <?php $image = $block->getImage($category);?>
                        <div class="js_slide flex-shrink-0 w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/6 p-2"
                             role="group"
                             aria-label="<?= $escaper->escapeHtmlAttr($category->getName()) ?>"
                        >
                            <a href="<?= $escaper->escapeUrl($category->getUrl()) ?>" class="block text-center hover:underline">
                                <img
                                    class="mx-auto"
                                    src="<?= $escaper->escapeUrl($image->getUrl()) ?>"
                                    alt="<?= $escaper->escapeHtmlAttr($category->getName()) ?>"
                                    style="aspect-ratio: <?= $image->getWidth() . ' / ' . $image->getHeight() ?>;"
                                    loading="lazy"
                                />
                                <?php if ($block->getData('show_name') === 'true'): ?>
                                    <strong class="block mt-2 font-semibold leading-tight"><?= $escaper->escapeHtml($category->getName()) ?></strong>
                                <?php endif; ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div>
                <template x-if="itemCount > pageSize">
                    <div
                        class="flex items-center justify-center pt-4"
                        :id="$id('slider-nav')"
                    >
                        <div class="flex flex-wrap w-full md:w-auto justify-center">
                            <?php for ($i=0; $i < $itemCount; $i++): ?>
                                <button
                                    type="button"
                                    :class="{
                                        'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                                    }"
                                    :aria-current="active === <?= (int) $i ?>"
                                    :aria-label="hyva.str('<?= $escaper->escapeJs(__('Display slide %1')) ?>', (<?= (int) $i ?> / pageSize) + 1)"
                                    @click="scrollTo(<?= (int) $i ?>)"
                                >
                                <span
                                    class="shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                    :class="{
                                        'bg-opacity-100': active === <?= (int) $i ?>,
                                        'bg-opacity-25': active !== <?= (int) $i ?>,
                                        'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                                    }"
                                    @click="scrollTo(<?= (int) $i ?>)"
                                ></span>
                                </button>
                            <?php endfor; ?>
                        </div>
                    </div>
                </template>
            </div>
        </div>
    </section>
<?php endif; ?>
