<?php
/** @var CategoriesList $block */

/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use ParadoxLabs\PageBuilderWidgets\Block\Category\CategoriesList;

?>
<?php if ($block->getCategoryCollection() && $block->getCategoryCollection()->getSize()): ?>
    <?php $categories = $block->getCategoryCollection()->getItems() ?>
    <ul class="glider-contain clear widget-product-carousel">
        <!-- TODO: Hyva compatible carousel and styling -->
        <div data-role="glider-content">
            <?php foreach ($categories as $category): ?>
                <li class="category-item">
                    <?php $image = $block->getImage($category); ?>
                    <a href="<?= $escaper->escapeUrl($category->getUrl()) ?>"
                       class="clear cat-info"
                       title="<?= $escaper->escapeHtmlAttr($category->getName()) ?>">
                        <div class="img">
                            <img class="object-contain"
                                 src="<?= $escaper->escapeUrl($image->getUrl()) ?>"
                                 alt="<?= $escaper->escapeHtmlAttr($category->getName()) ?>"
                                 width="<?= $image->getWidth() ?>"
                                 style="aspect-ratio: <?= $image->getWidth() . ' / ' . $image->getHeight() ?>;"
                                 loading="lazy"/>
                        </div>
                        <?php if ($block->getData('show_name') === 'true'): ?>
                            <span class="category-name">
                                <span><?= $escaper->escapeHtml($category->getName()) ?></span>
                                <span class="count">
                                    <?= $escaper->escapeHtml($category->getIndexedProductCount()) ?>
                                </span>
                            </span>
                            <p class="subtext"><?= $category->getThumbnailSubtext() ?></p>
                        <?php endif ?>
                    </a>
                </li>
            <?php endforeach ?>
        </div>
        <?= /** @noEscape */
        $block->getBlockHtml('pagebuilder.carousel.nav') ?>
    </ul>
<?php endif; ?>
